global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'swarm-ecommerce'

# Configuration des alertes (optionnel)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: 'A'
        port: 9100

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: 'A'
        port: 8080

  # Métriques de l'API Backend (si vous exposez /metrics)
  # - job_name: 'api-backend'
  #   dns_sd_configs:
  #     - names: ['tasks.api']
  #       type: 'A'
  #       port: 8080
  #   metrics_path: '/metrics'
